### ISSUE TITLE
Unaligned results

### ISSUE THREAD

**Issue by Steve-Tod** [DeokyunKim/Progressive-Face-Super-Resolution#12]
Hi, do your pre-trained models support unaligned inputs? I test it with unaligned inputs and got really bad results. But with aligned inputs, the results look great.
![image](https://user-images.githubusercontent.com/26958167/68446866-f6203d00-0218-11ea-8feb-c7db831b7072.png)

I found you show unaligned results in your paper, can you please provide the pre-trained model on that set? Thank you!

**Comment by Steve-Tod** [comment]
The picture above is test result of unaligned CelebA faces with generator_checkpoint_singleGPU.ckpt.

**Comment by DeokyunKim** [comment]
The trained model we uploaded is trained by aligned face images.

**Comment by Steve-Tod** [comment]
Thanks, can you please also upload the model trained with unaligned ones?

**Comment by DeokyunKim** [comment]
I uploaded 'unalign_trained_generator_checkpoint.ckpt'.

**Comment by Steve-Tod** [comment]
Thank you so much! Another thing I found interesting is that when running your evaluation code, different batch size gives different PSNR result.
