### ISSUE TITLE
NameError: name 'predict_image' is not defined

### ISSUE THREAD

**Issue by marshonhuckleberry** [DeokyunKim/Progressive-Face-Super-Resolution#15]
pre-trained model is loaded step:3, alpha:1 iteration:80000
traceback (most recent call last):
File "..\eval.py", line 99, in
..
File "..\eval.py", line 29, in test
..
**NameError: name 'predict_image' is not defined**

**Comment by DeokyunKim** [comment]
Thanks, marshonhuckleberry! I modified eval.py code.
