### ISSUE TITLE
Distorted image outputs 

### ISSUE THREAD

**Issue by kushalchordiya216** [DeokyunKim/Progressive-Face-Super-Resolution#19]
I have tried running the demo.py script to use the pretrained ckpt file included in your repo, to upscale images from the celeba dataset, but the output images are always highly distorted. Is there some kind of preprocessing that needs to be done on the images before running demo.py
input
![000010](https://user-images.githubusercontent.com/34130680/86521361-64cb9e00-be6d-11ea-89bf-6d601a96f1cb.jpg)

output
![face_op](https://user-images.githubusercontent.com/34130680/86521349-2f26b500-be6d-11ea-9ab8-9757c91386a2.jpeg)

All images i have tried so far have had similar results

**Comment by Gauravajariwal11** [comment]
did you find any solution to it??

**Comment by DeokyunKim** [comment]
Hi, thank you guys for your interest in our work.

Before resizing image to 128x128 pixels, We cropped images to 178x178 pixels for removing the background. (we use torchvision.transforms.CenterCrop((178, 178)) )

we note that we can not show you guys the exact hyper-parameters because of company research project.

Thanks in advance your understanding.

**Comment by Gauravajariwal11** [comment]
@DeokyunKim  Yes, that is what I was thinking. While I understand that it may not be possible, but do you think we can get the training code for this paper? I am trying to implement this for my research project. It would be of great help. 

If not, then that is fine. :)

**Comment by kushalchordiya216** [comment]
> Hi, thank you guys for your interest in our work.
> 
> Before resizing image to 128x128 pixels, We cropped images to 178x178 pixels to remove the background. (we use torchvision.transforms.CenterCrop((178, 178)) )
> 
> we note that we can not show you guys the exact hyper-parameters because of company research project.
> 
> Thanks in advance your understanding.

I understand. Thank you for responding.
