### ISSUE TITLE
About eval

### ISSUE THREAD

**Issue by JR-Wang** [DeokyunKim/Progressive-Face-Super-Resolution#4]
I tried your eval.py，but predicted_image seems to be a picture of noise.  I have confirmed input_image got from the code below, 
input_image = input_image.to(device)
        if step==1:
            target_image = x2_target_image.to(device)
        elif step==2:
            target_image = x4_target_image.to(device)
        else:
            target_image = target_image.to(device)

        input_image = input_image.to(device)
and it is a 16*16 image. May I ask what's wrong with my predicted_image? Many thanks for your answer.

**Comment by DeokyunKim** [comment]
Did you use the pretrained model (generator_checkpoint_singleGPU.ckpt)? The other model is a distributed trained version.

**Comment by JR-Wang** [comment]
Many thanks for your timely reply!
Below is my last operation.
python eval.py --data-path './dataset' --checkpoint-path 'CHECKPOINT_PATH/generator_checkpoint.ckpt'
I changed the model to generator_checkpoint_singleGPU.ckpt and got correct result. So I wonder if you may revise your README?

**Comment by DeokyunKim** [comment]
Sure, There was a mistake. Thank you for your feedback :)
